"""initial

Revision ID: e4384232efa6
Revises: 
Create Date: 2026-05-25 23:41:43.036126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4384232efa6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('cpt_code', sa.String(), nullable=False),
    sa.Column('diagnosis_code', sa.String(), nullable=False),
    sa.Column('insurance_payer', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'VALIDATED', 'SUBMITTED', 'ADJUDICATED', 'PAID', 'DENIED', name='claimstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('CREATED', 'VALIDATED', 'SUBMITTED', 'ADJUDICATED', 'PAID', 'DENIED', name='claimstatus', native_enum=False), nullable=False),
    sa.Column('to_status', sa.Enum('CREATED', 'VALIDATED', 'SUBMITTED', 'ADJUDICATED', 'PAID', 'DENIED', name='claimstatus', native_enum=False), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_events')
    op.drop_table('claims')
    # ### end Alembic commands ###
